language: node_js

node_js:
  - "node"
  - "8"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

script:
  - yarn test

cache:
  yarn: true
  directories:
    - "node_modules"
