name: "ci-test-2312"
on: { push: { branches: [ "**" ], tags: [ "v*" ] } } # use `v0.0.0` tag pattern # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#onpushbranchestagsbranches-ignoretags-ignore
env: { "IS_CI": true }
jobs:
  "test-base": # job id
    strategy: { fail-fast: false, matrix: { OS: [ "ubuntu-24.04" ] } }
    runs-on: "${{ matrix.OS }}" # https://docs.github.com/en/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for--private-repositories
    timeout-minutes: 15
    steps:
      - { uses: "actions/checkout@v7" } # https://github.com/actions/checkout
      - { uses: "actions/setup-node@v7", with: { node-version: "24" } } # https://github.com/actions/setup-node
      - run: npm ci --ignore-scripts
      - run: npm test

  "test-extra": # job id
    needs: [ "test-base" ] # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idneeds
    strategy: { fail-fast: false, matrix: { OS: [ "ubuntu-24.04-arm", "windows-latest", "macos-latest" ] } }
    runs-on: "${{ matrix.OS }}"
    timeout-minutes: 15
    steps:
      - { uses: "actions/checkout@v7" } # https://github.com/actions/checkout
      - { uses: "actions/setup-node@v7", with: { node-version:  "24" } } # https://github.com/actions/setup-node
      - run: npm ci --ignore-scripts
      - run: npm test
        env: { "IS_CI_LITE": true }

  "publish-tag": # job id
    if: "github.ref_type == 'tag'" # only run on git tag push
    needs: [ "test-base", "test-extra" ] # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idneeds
    runs-on: "ubuntu-24.04"
    timeout-minutes: 15
    steps:
      - { uses: "actions/checkout@v7" } # https://github.com/actions/checkout
      - { uses: "actions/setup-node@v7", with: { node-version: "24" } } # https://github.com/actions/setup-node
      - run: npm ci --ignore-scripts
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN_DR_JS }}" > .npmrc # TODO: need change to npm trusted publishing: https://docs.npmjs.com/trusted-publishers
      - run: npm run script-publish
