name: ci-test

on:
  push:
    branches:
      - '**'

jobs:
  build:
    strategy:
      fail-fast: false # allow all test to run to the end
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node-version: [ 12.x, 14.x, 15.4, 15.5 ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Git repo
        uses: actions/checkout@v2 # https://github.com/actions/checkout

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1 # https://github.com/actions/setup-node
        with:
          node-version: ${{ matrix.node-version }}

      - run: node test-nodejs-v15.5.0-http-stream-destroyed.js
