name: ci-test-tag

on: # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
  push: { tags: [ "v*" ] } # use `v0.0.0` tag pattern

env:
  cache-version: 20220513
  cache-path: | # actually "\n" separated string
    .github/cache/persist-gitignore/
    ~/.npm/
  IS_CI: true

jobs:
  test-tag: # job id
    timeout-minutes: 15
    strategy:
      fail-fast: false # allow all test to run to the end
      matrix:
        os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]
        node-version: [ "18.x" ]
        include: [ { os: "ubuntu-latest", node-version: "14.x" } ]
    runs-on: "${{ matrix.os }}"
    steps:
      - { uses: "actions/checkout@v2" } # https://github.com/actions/checkout
      - { uses: "actions/setup-node@v2", with: { node-version: "${{ matrix.node-version }}" } } # https://github.com/actions/setup-node
      - run: npx @dr-js/dev@0.4 -eI .github/ci-patch.js
      - run: dr-dev -c .github/cache/config.js --cache-step setup
      - { uses: "actions/cache@v2", with: { # https://github.com/actions/cache
        key: "${{ runner.os }}-${{ env.cache-version }}-${{ matrix.node-version }}-${{ hashFiles('.github/cache/temp-gitignore/checksum-file') }}",
        restore-keys: "${{ runner.os }}-${{ env.cache-version }}-${{ matrix.node-version }}-",
        path: "${{ env.cache-path }}"
      } }
      - run: dr-dev -c .github/cache/config.js --cache-step mark
      - run: npm8 ci --no-optional # TODO: wait for npm@7 adoption and try npm install + cache for faster puppeteer install
      - run: npm test
      - run: dr-dev -c .github/cache/config.js --cache-step prune

  publish-tag: # job id
    needs: [ "test-tag" ] # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idneeds
    timeout-minutes: 15
    runs-on: "ubuntu-latest"
    steps:
      - { uses: "actions/checkout@v2" } # https://github.com/actions/checkout
      - { uses: "actions/setup-node@v2", with: { node-version: "16.x" } } # https://github.com/actions/setup-node
      - run: npx @dr-js/dev@0.4 -eI .github/ci-patch.js
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN_DR_JS }}" > .npmrc
      - run: npm8 ci --no-optional
      - run: npm run script-publish
